### ISSUE TITLE
Хотелось бы играть на поле не только 3х3 но и 4х4

### ISSUE THREAD

**Issue by yp-rep** [Pavlitto/nuclear-repos#2]
Добрый день, хотелось бы играть на поле 4х4, доработайте пожалуйста свою программу.

**Comment by Pavlitto** [comment]
Уважаемый yp-rep, вы наверное не скачивали программу, она уже разработана с учетом того что можно использовать поле 3х3 и 4х4, выбор происходит при старте новой игры.
